import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Exam-Tool",
	description: "Generated by create next app",
};
import AuthProvider from "../context/AuthProvider";
import ToastProvider from "../toast-provider";
import "react-toastify/dist/ReactToastify.css";

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<AuthProvider>
			<Navbar />
			<ToastProvider>{children}</ToastProvider>
		</AuthProvider>
	);
}
