import AdminSidebar from "@/components/admin-sidebar";
import { GraduationCap, LayoutDashboard, LogOut, Users } from "lucide-react";
import Link from "next/link";
export const metadata = {
	title: "Admin dashboard",
	description: "Generated by Next.js",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<div className="flex flex-row  w-full h-screen">
			<AdminSidebar />
			<main className="w-full">{children}</main>
		</div>
	);
}
