import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "prismjs/themes/prism-tomorrow.css"; // Import a theme (choose a theme you like)
import "prismjs"; // Import Prism.js
import AuthProvider from "./context/AuthProvider";
import ToastProvider from "./toast-provider";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Exam-Tool",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={inter.className}

				// onCopy={() => {
				// 	return false;
				// }}
				// onCut="return false"
				// onPaste="return false"
			>
				<ToastProvider>
					<AuthProvider>{children}</AuthProvider>
				</ToastProvider>
			</body>
		</html>
	);
}
