import { authOptions } from "@/app/api/auth/[...nextauth]/auth";
import DashboardSidebar from "@/components/dashboard/dashboard-sidebar";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
export const metadata = {
	title: "Dashboard",
	description: "Generated by Next.js",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await getServerSession(authOptions);
	if (!session) {
		redirect("/auth/login?redirect=/dashboard");
	}
	return (
		<div className="flex flex-row h-screen">
			<DashboardSidebar session={session} />
			<main className=" w-full">{children}</main>
		</div>
	);
}
